version: "2.4"
services:
  # Web Server
  app:
    build:
      context: .
    depends_on: 
      mysql:
        condition: service_healthy
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret

  # Database
  mysql:
    # use bitnami/mysql:5.7 because it has arm version image
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h localhost
    environment:
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=example_root_password
      - MYSQL_DATABASE=homestead
    volumes:
      - ./mysql/data:/var/lib/mysql
    logging:
      driver: none

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example_root_password
    ports:
      - "8181:80"
    depends_on:
      - mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"